from ninja import Router, Schema
from typing import List, Optional
from django.shortcuts import get_object_or_404
from django.db import transaction
from products.models.chicken import ChickenItem
from users.views import AuthBearer

router = Router()


# ============================================================================
# ADMIN-ONLY AUTHENTICATION
# ============================================================================

class AdminAuthBearer(AuthBearer):
    """Authentication class that only allows admin/staff users"""
    def authenticate(self, request, token):
        user = super().authenticate(request, token)
        if user and (user.is_staff or user.is_superuser):
            return user
        return None


# ============================================================================
# SCHEMAS FOR CHICKEN DATA FORMAT
# ============================================================================

# Request schemas (what the client sends) - ID is optional or not included
class ChickenItemCreateSchema(Schema):
    """Schema for creating a new chicken item (ID is auto-generated)"""
    name: str
    price: float
    image: str
    description: str = ''


# Response schemas (what the API returns) - ID is always included
class ChickenItemResponseSchema(Schema):
    """Schema for returning chicken item data (includes auto-generated ID)"""
    id: int
    name: str
    price: float
    image: str
    description: str = ''


class ChickenDataSchema(Schema):
    category: str
    items: List[ChickenItemResponseSchema]


class ChickenItemUpdateSchema(Schema):
    name: Optional[str] = None
    price: Optional[float] = None
    image: Optional[str] = None
    description: Optional[str] = None


# ============================================================================
# CHICKEN DATA FORMAT CRUD ENDPOINTS
# ============================================================================

@router.get("/chicken/data", response=ChickenDataSchema)
def get_chicken_data(request):
    """Get all chicken items in the specified format (Public - no auth required)"""
    # Get all chicken items
    items_queryset = ChickenItem.objects.all()
    
    items = [
        {
            'id': item.id,
            'name': item.name,
            'price': float(item.price),
            'image': item.image,
            'description': item.description
        }
        for item in items_queryset
    ]
    
    return {
        'category': 'Chicken',
        'items': items
    }


@router.post("/chicken/data", response={201: ChickenDataSchema}, auth=AdminAuthBearer())
def create_chicken_items(request, payload: ChickenDataSchema):
    """Create multiple chicken items from the specified format (ADMIN ONLY)"""
    created_items = []
    
    with transaction.atomic():
        for item_data in payload.items:
            # Create or update chicken item
            item, created = ChickenItem.objects.update_or_create(
                name=item_data.name,
                defaults={
                    'price': item_data.price,
                    'image': item_data.image,
                    'description': item_data.description
                }
            )
            
            created_items.append({
                'id': item.id,
                'name': item.name,
                'price': float(item.price),
                'image': item.image,
                'description': item.description
            })
    
    return 201, {
        'category': 'Chicken',
        'items': created_items
    }


@router.post("/chicken/items", response={201: ChickenItemResponseSchema}, auth=AdminAuthBearer())
def create_single_chicken_item(request, payload: ChickenItemCreateSchema):
    """Create a single chicken item (ADMIN ONLY)"""
    # Create chicken item - ID is auto-generated by Django
    item = ChickenItem.objects.create(
        name=payload.name,
        price=payload.price,
        image=payload.image,
        description=payload.description
    )
    
    return 201, {
        'id': item.id,
        'name': item.name,
        'price': float(item.price),
        'image': item.image,
        'description': item.description
    }


@router.put("/chicken/items/{item_id}", response=ChickenItemResponseSchema, auth=AdminAuthBearer())
def update_chicken_item(request, item_id: int, payload: ChickenItemUpdateSchema):
    """Update a specific chicken item by ID (ADMIN ONLY)"""
    # Find the item by ID (faster and more reliable)
    item = get_object_or_404(ChickenItem, id=item_id)
    
    # Update fields if provided
    if payload.name is not None:
        item.name = payload.name
    
    if payload.price is not None:
        item.price = payload.price
    
    if payload.image is not None:
        item.image = payload.image
    
    if payload.description is not None:
        item.description = payload.description
    
    item.save()
    
    return {
        'id': item.id,
        'name': item.name,
        'price': float(item.price),
        'image': item.image,
        'description': item.description
    }


@router.delete("/chicken/items/{item_id}", auth=AdminAuthBearer())
def delete_chicken_item(request, item_id: int):
    """Delete a specific chicken item by ID (ADMIN ONLY)"""
    # Find and delete the item by ID (faster and more reliable)
    item = get_object_or_404(ChickenItem, id=item_id)
    
    item_name = item.name
    item.delete()
    
    return {
        'status': 'success',
        'message': f'{item_name} (ID: {item_id}) deleted successfully'
    }
