from ninja import Router, Schema
from typing import List, Optional
from django.shortcuts import get_object_or_404
from django.db import transaction
from products.models.dry_fruits import DryFruit
from users.views import AuthBearer

router = Router()


# ============================================================================
# ADMIN-ONLY AUTHENTICATION
# ============================================================================

class AdminAuthBearer(AuthBearer):
    """Authentication class that only allows admin/staff users"""
    def authenticate(self, request, token):
        user = super().authenticate(request, token)
        if user and (user.is_staff or user.is_superuser):
            return user
        return None


# ============================================================================
# SCHEMAS FOR DRY FRUIT DATA FORMAT
# ============================================================================

# Request schemas (what the client sends) - ID is optional or not included
class DryFruitCreateSchema(Schema):
    """Schema for creating a new dry fruit item (ID is auto-generated)"""
    name: str
    price: float
    image: str
    description: str = ''


# Response schemas (what the API returns) - ID is always included
class DryFruitResponseSchema(Schema):
    """Schema for returning dry fruit item data (includes auto-generated ID)"""
    id: int
    name: str
    price: float
    image: str
    description: str = ''


class DryFruitDataSchema(Schema):
    category: str
    items: List[DryFruitResponseSchema]


class DryFruitUpdateSchema(Schema):
    name: Optional[str] = None
    price: Optional[float] = None
    image: Optional[str] = None
    description: Optional[str] = None


# ============================================================================
# DRY FRUIT DATA FORMAT CRUD ENDPOINTS
# ============================================================================

@router.get("/dry-fruits/data", response=DryFruitDataSchema)
def get_dryfruits_data(request):
    """Get all dry fruit items in the specified format (Public - no auth required)"""
    # Get all dry fruit items
    items_queryset = DryFruit.objects.all()
    
    items = [
        {
            'id': item.id,
            'name': item.name,
            'price': float(item.price),
            'image': item.image,
            'description': item.description
        }
        for item in items_queryset
    ]
    
    return {
        'category': 'Dry Fruits',
        'items': items
    }


@router.post("/dry-fruits/data", response={201: DryFruitDataSchema}, auth=AdminAuthBearer())
def create_dryfruits_items(request, payload: DryFruitDataSchema):
    """Create multiple dry fruit items from the specified format (ADMIN ONLY)"""
    created_items = []
    
    with transaction.atomic():
        for item_data in payload.items:
            # Create or update dry fruit item
            item, created = DryFruit.objects.update_or_create(
                name=item_data.name,
                defaults={
                    'price': item_data.price,
                    'image': item_data.image,
                    'description': item_data.description
                }
            )
            
            created_items.append({
                'id': item.id,
                'name': item.name,
                'price': float(item.price),
                'image': item.image,
                'description': item.description
            })
    
    return 201, {
        'category': 'Dry Fruits',
        'items': created_items
    }


@router.post("/dry-fruits/items", response={201: DryFruitResponseSchema}, auth=AdminAuthBearer())
def create_single_dryfruit_item(request, payload: DryFruitCreateSchema):
    """Create a single dry fruit item (ADMIN ONLY)"""
    # Create dry fruit item - ID is auto-generated by Django
    item = DryFruit.objects.create(
        name=payload.name,
        price=payload.price,
        image=payload.image,
        description=payload.description
    )
    
    return 201, {
        'id': item.id,
        'name': item.name,
        'price': float(item.price),
        'image': item.image,
        'description': item.description
    }


@router.put("/dry-fruits/items/{item_id}", response=DryFruitResponseSchema, auth=AdminAuthBearer())
def update_dryfruit_item(request, item_id: int, payload: DryFruitUpdateSchema):
    """Update a specific dry fruit item by ID (ADMIN ONLY)"""
    # Find the item by ID (faster and more reliable)
    item = get_object_or_404(DryFruit, id=item_id)
    
    # Update fields if provided
    if payload.name is not None:
        item.name = payload.name
    
    if payload.price is not None:
        item.price = payload.price
    
    if payload.image is not None:
        item.image = payload.image
    
    if payload.description is not None:
        item.description = payload.description
    
    item.save()
    
    return {
        'id': item.id,
        'name': item.name,
        'price': float(item.price),
        'image': item.image,
        'description': item.description
    }


@router.delete("/dry-fruits/items/{item_id}", auth=AdminAuthBearer())
def delete_dryfruit_item(request, item_id: int):
    """Delete a specific dry fruit item by ID (ADMIN ONLY)"""
    # Find and delete the item by ID (faster and more reliable)
    item = get_object_or_404(DryFruit, id=item_id)
    
    item_name = item.name
    item.delete()
    
    return {
        'status': 'success',
        'message': f'{item_name} (ID: {item_id}) deleted successfully'
    }
