from ninja import Router, Schema
from typing import List, Optional
from django.shortcuts import get_object_or_404
from django.db import transaction
from products.models.sweets import Sweet
from users.views import AuthBearer

router = Router()


# ============================================================================
# ADMIN-ONLY AUTHENTICATION
# ============================================================================

class AdminAuthBearer(AuthBearer):
    """Authentication class that only allows admin/staff users"""
    def authenticate(self, request, token):
        user = super().authenticate(request, token)
        if user and (user.is_staff or user.is_superuser):
            return user
        return None


# ============================================================================
# SCHEMAS FOR SWEET DATA FORMAT
# ============================================================================

# Request schemas (what the client sends) - ID is optional or not included
class SweetCreateSchema(Schema):
    """Schema for creating a new sweet item (ID is auto-generated)"""
    name: str
    price: float
    image: str
    description: str = ''


# Response schemas (what the API returns) - ID is always included
class SweetResponseSchema(Schema):
    """Schema for returning sweet item data (includes auto-generated ID)"""
    id: int
    name: str
    price: float
    image: str
    description: str = ''


class SweetDataSchema(Schema):
    category: str
    items: List[SweetResponseSchema]


class SweetUpdateSchema(Schema):
    name: Optional[str] = None
    price: Optional[float] = None
    image: Optional[str] = None
    description: Optional[str] = None


# ============================================================================
# SWEET DATA FORMAT CRUD ENDPOINTS
# ============================================================================

@router.get("/sweets/data", response=SweetDataSchema)
def get_sweets_data(request):
    """Get all sweet items in the specified format (Public - no auth required)"""
    # Get all sweet items
    items_queryset = Sweet.objects.all()
    
    items = [
        {
            'id': item.id,
            'name': item.name,
            'price': float(item.price),
            'image': item.image,
            'description': item.description
        }
        for item in items_queryset
    ]
    
    return {
        'category': 'Sweets',
        'items': items
    }


@router.post("/sweets/data", response={201: SweetDataSchema}, auth=AdminAuthBearer())
def create_sweets_items(request, payload: SweetDataSchema):
    """Create multiple sweet items from the specified format (ADMIN ONLY)"""
    created_items = []
    
    with transaction.atomic():
        for item_data in payload.items:
            # Create or update sweet item
            item, created = Sweet.objects.update_or_create(
                name=item_data.name,
                defaults={
                    'price': item_data.price,
                    'image': item_data.image,
                    'description': item_data.description
                }
            )
            
            created_items.append({
                'id': item.id,
                'name': item.name,
                'price': float(item.price),
                'image': item.image,
                'description': item.description
            })
    
    return 201, {
        'category': 'Sweets',
        'items': created_items
    }


@router.post("/sweets/items", response={201: SweetResponseSchema}, auth=AdminAuthBearer())
def create_single_sweet_item(request, payload: SweetCreateSchema):
    """Create a single sweet item (ADMIN ONLY)"""
    # Create sweet item - ID is auto-generated by Django
    item = Sweet.objects.create(
        name=payload.name,
        price=payload.price,
        image=payload.image,
        description=payload.description
    )
    
    return 201, {
        'id': item.id,
        'name': item.name,
        'price': float(item.price),
        'image': item.image,
        'description': item.description
    }


@router.put("/sweets/items/{item_id}", response=SweetResponseSchema, auth=AdminAuthBearer())
def update_sweet_item(request, item_id: int, payload: SweetUpdateSchema):
    """Update a specific sweet item by ID (ADMIN ONLY)"""
    # Find the item by ID (faster and more reliable)
    item = get_object_or_404(Sweet, id=item_id)
    
    # Update fields if provided
    if payload.name is not None:
        item.name = payload.name
    
    if payload.price is not None:
        item.price = payload.price
    
    if payload.image is not None:
        item.image = payload.image
    
    if payload.description is not None:
        item.description = payload.description
    
    item.save()
    
    return {
        'id': item.id,
        'name': item.name,
        'price': float(item.price),
        'image': item.image,
        'description': item.description
    }


@router.delete("/sweets/items/{item_id}", auth=AdminAuthBearer())
def delete_sweet_item(request, item_id: int):
    """Delete a specific sweet item by ID (ADMIN ONLY)"""
    # Find and delete the item by ID (faster and more reliable)
    item = get_object_or_404(Sweet, id=item_id)
    
    item_name = item.name
    item.delete()
    
    return {
        'status': 'success',
        'message': f'{item_name} (ID: {item_id}) deleted successfully'
    }
