# Generated by Django 6.0.6 on 2026-08-13 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_chickenitem_alter_product_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chickenitem',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
