# Generated by Django 6.0.6 on 2026-08-14 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_chickenitem_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='DryFruit',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=300, unique=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AlterModelOptions(
            name='chickenitem',
            options={'ordering': ['id']},
        ),
        migrations.AlterField(
            model_name='chickenitem',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AddIndex(
            model_name='chickenitem',
            index=models.Index(fields=['id'], name='products_ch_id_7d24f5_idx'),
        ),
        migrations.AddIndex(
            model_name='dryfruit',
            index=models.Index(fields=['id'], name='products_dr_id_17d044_idx'),
        ),
    ]
